---
version: "3.8"
services:
  api:
    container_name: simpleapi
    restart: always
    build:
      context: ../src/SimpleApi
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    depends_on:
      - mongo
  mongo:
    container_name: mongoSimpleApi
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017