---
version: "3.8"
services:
  api:
    container_name: simpleapi
    restart: always
    build:
      context: ../src/SimpleApi
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongoSimpleApi
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379